language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm:
      - ruby-head
      - rbx-2
sudo: false
