language: ruby
rvm:
  - ruby-1.8.7-p371
  - ruby-1.9.3-p551
  - ruby-2.0.0-p648
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - jruby-1.7.26
  - jruby-9.0.5.0
  - jruby-9.1.9.0
  - ruby-head
matrix:
  allow_failures:
    - rvm:
      - ruby-head
os: linux
dist: trusty
sudo: false
